# Generated by Django 4.2.4 on 2023-08-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonspecies',
            name='national_pokedex_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
