# Generated by Django 4.2.4 on 2023-08-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemonspecies_national_pokedex_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonmonster',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
