# Generated by Django 4.2.4 on 2023-08-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_pokemoncategory_pokemonspecies_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecies',
            name='national_pokedex_number',
            field=models.IntegerField(unique=True),
        ),
    ]
