# Generated by Django 4.2.4 on 2023-08-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_alter_pokemonspecies_national_pokedex_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonmonster',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=6),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='category',
            field=models.ManyToManyField(null=True, to='pokemon.pokemoncategory'),
        ),
    ]
