# Generated by Django 4.2.4 on 2023-08-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_pokemonmonster_gender_alter_pokemonspecies_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecies',
            name='category',
            field=models.ManyToManyField(blank=True, to='pokemon.pokemoncategory'),
        ),
    ]
