# Generated by Django 4.2.4 on 2023-08-26 17:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_pokemonspecies_if_genderless_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemontype',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
