# Generated by Django 4.2.4 on 2023-08-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0009_pokemontype_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonspecies',
            name='category',
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='if_legendary',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='if_starter',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='PokemonCategory',
        ),
    ]
