# Generated by Django 4.2.4 on 2023-08-27 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemon', '0010_remove_pokemonspecies_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonmonster',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='if_genderless',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='if_legendary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='if_starter',
            field=models.BooleanField(default=False),
        ),
    ]
