# Generated by Django 4.2.4 on 2023-08-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0011_pokemonmonster_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonspecies',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
