# Generated by Django 4.2.4 on 2023-08-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0012_pokemonspecies_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonmonster',
            name='exp',
            field=models.IntegerField(default=-1, editable=False),
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='evolve_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='evolve_species',
            field=models.ManyToManyField(to='pokemon.pokemonspecies'),
        ),
        migrations.AddField(
            model_name='pokemonspecies',
            name='if_evolve_by_level_up',
            field=models.BooleanField(default=False),
        ),
    ]
