# Generated by Django 4.2.4 on 2023-08-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0013_pokemonmonster_exp_pokemonspecies_evolve_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonspecies',
            name='evolve_species',
            field=models.ManyToManyField(blank=True, to='pokemon.pokemonspecies'),
        ),
        migrations.AlterField(
            model_name='pokemonspecies',
            name='short_description',
            field=models.CharField(max_length=200),
        ),
    ]
