# Generated by Django 4.2.4 on 2023-08-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0014_alter_pokemonspecies_evolve_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonspecies',
            name='picture_source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
